### ISSUE TITLE
Downloading Brains tutorial

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#122]
The tutorial [here](https://brainlight.readthedocs.io/en/documentation/notebooks/utils/downloading_brains.html), does not work for me. When I copy the code blocks into a script and run it, here is the output:

Downloaded volume is of shape (151, 3, 3), with total intensity 54614.
Selected volume contains 2 nodes and 1 paths
Traceback (most recent call last):
  File "download_brains.py", line 23, in <module>
    viewer.add_image(img)
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\components\add_layers_mixin.py", line 228, in add_image
    return self.add_layer(layers.Image(data, **kwargs))
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\components\add_layers_mixin.py", line 60, in add_layer
    self.layers.append(layer)
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\utils\list\_model.py", line 60, in append
    self.events.added(item=obj, index=len(self) - 1)
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\utils\event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\utils\event.py", line 525, in _invoke_callback
    _handle_exception(
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\utils\event.py", line 523, in _invoke_callback
    cb(event)
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\utils\event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\utils\event.py", line 525, in _invoke_callback
    _handle_exception(
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\utils\event.py", line 523, in _invoke_callback
    cb(event)
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\components\viewer_model.py", line 510, in _update_grid
    self.grid_view(
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\components\viewer_model.py", line 500, in grid_view
    self._subplot(layer, (i_row, i_column))
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\components\viewer_model.py", line 528, in _subplot
    scene_size, corner = self._scene_shape()
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\components\viewer_model.py", line 266, in _scene_shape
    size = [size[i] for i in self.dims.displayed]
  File "c:\users\thomas athey\documents\labs\labs\miller\mouselight\napari\napari\components\viewer_model.py", line 266, in <listcomp>
    size = [size[i] for i in self.dims.displayed]
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by tathey1** [comment]
works now
